FROM golang:1.21-alpine AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN go build -o /nameserver ./cmd/nameserver
RUN go build -o /orchestrator ./cmd/orchestrator

FROM alpine:latest
COPY --from=builder /nameserver /nameserver
COPY --from=builder /orchestrator /orchestrator